language: c
sudo: false
dist: xenial
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - REVDEPS="ppx_deriving_hardcaml
      ppx_deriving_crowbar
      ppx_deriving_yojson
      ppx_deriving_madcast
      ppx_deriving_protocol
      ppx_deriving_rpc
      ppx_deriving_argparse
      ppx_deriving_cmdliner
      ppx_deriving_protobuf
      ppx_deriving_morphism
      visitors"
 ocaml_version:
            - 4.11
            - 4.10
            - 4.09
            - 4.08
            - 4.07
            - 4.06
            - 4.05
 arch:
  - amd64
  - ppc64le
os:
  - linux
